version: "3"

services:
  node_docker:
    image: node:10-alpine
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    command: /bin/sh -c "npm install && npm run start:dev"